authors:
  jumashafara:
    name: Juma Shafara
    description: Data Scientist at Raising the Village and Instructor at DATAIDEA
    avatar: https://github.com/jumashafara.png
    url: https://jumashafara.dataidea.org